Function request
WildCodeSchool/tlse0320-p2-CataclysmPredictor pull request #17
Opened 2020-04-23 10:29 UTC by Anthony31400

Ajouts d'un système de requête api en fonction d'une date et stockage de résultat dans le state

2020-04-23 14:24 UTC, Alpasc submitted a review, later dismissed

2020-04-23 14:24 UTC, Alpasc commented on src/components/ComponentMain/GlobalContainer.jsx
> +    const url = `https://api.nasa.gov/neo/rest/v1/feed?start_date=${date}&api_key=DEMO_KEY`;
changer demokey par la clé enregistrée

2020-04-24 08:38 UTC, Froyj commented on src/components/ComponentMain/GlobalContainer.jsx
> +    const url = `https://api.nasa.gov/neo/rest/v1/feed?start_date=${date}&api_key=DEMO_KEY`;
:+1

2020-04-24 08:39 UTC, Froyj approved these changes

2020-04-24 08:40 UTC, Froyj requested changes

2020-04-24 08:40 UTC, Froyj commented on src/components/ComponentMain/GlobalContainer.jsx
> +    const { displayScenarios } = this.state.displayBottomContent;
```suggestion
    const { displayFooter, displayArticle, displayCriteres, displayScenarios } = this.state.displayBottomContent
```

2020-04-27 07:37 UTC, Justine810 approved these changes

2020-04-30 08:55 UTC, Froyj approved these changes
utACK

2020-05-01 11:59 UTC, merged