Init ui
WildCodeSchool/tlse0320-p2-CataclysmPredictor pull request #3
Opened 2020-04-17 15:38 UTC by Anthony31400

PR1: Création de l'interface utilisateur comprenant :
Page accueil avec bouton d'entrée sur l'application.
Requête image du jour fonctionnelle.
Création des composants boutons pour la navigation.
Création composant titre.
Création du composant Container qui contiendra l'ensemble des composant de l'application.

2020-04-20 09:53 UTC, Froyj requested changes
Séparer l'affichage de l'image du jour avec requête API du reste de la PR qui concerne affichage de données statiques. Faire 2 PR et vous assurer qu'il n'y a pas d'autres User Stories incluses dans la même PR

2020-04-22 07:58 UTC, Anthony31400 commented
La PR a changé, le composant Welcome a été supprimer pour être proposer dans une autre PR. Cette PR est à valider en premier

2020-04-22 14:22 UTC, Froyj commented on src/components/ComponentBottom/CriteresContent.jsx
> +      <div className="heigth" />
pas de div auto-fermantes

2020-04-22 14:30 UTC, Froyj approved these changes
Remettre le app.test.jsx en js

2020-04-22 14:58 UTC, Anthony31400 commented on src/components/Buttons/Buttons.css
> +  /*background-color: rgb(89, 247, 247);*/
Supprimer les lignes en commentaires checker différences de hover entre les boutons du haut et les boutons du bas

2020-04-22 14:59 UTC, Anthony31400 commented on src/components/ComponentBottom/ArticleContent.jsx
> +      <div className="heigth" />
Pas de div auto fermante ==> inutile, autant supprimer le composant

2020-04-22 15:01 UTC, Anthony31400 commented on src/components/ComponentBottom/Content.css
> +.footer {
Séparer CSS propre au footer du reste des composants déroulant, travailler une animation de déroulement

2020-04-22 15:08 UTC, Anthony31400 reviewed
ok regarder les commentaires laissés

2020-04-22 15:08 UTC, Anthony31400 commented on src/components/ComponentBottom/FooterContent.jsx
> +        <li className="marge-large inline" />
Ajouter les images vers les réseaux sociaux

2020-04-22 15:08 UTC, Anthony31400 commented on src/components/ComponentMain/GlobalContainer.jsx
> +export default GlobalContainer;
Factoriser l'appel des <ButtonBottom />

2020-04-22 15:08 UTC, Anthony31400 commented on src/components/ComponentMain/MainApp.jsx
> +export default MainApp;
changer les div par des images

2020-04-22 15:08 UTC, Anthony31400 commented on src/components/ComponentMain/MainTitle.css
> +}
revoir la couleur de façon a ce que elle soit identique à celle utilisé pour les boutons, travailler le soulignement

2020-04-22 15:13 UTC, Alpasc approved these changes
par-fait !

2020-04-22 15:13 UTC, merged