Link calendar
WildCodeSchool/tlse0320-p2-CataclysmPredictor pull request #36
Opened 2020-05-01 13:00 UTC by Anthony31400

Liaison du calendrier au bouton période
création de composant pour les constantes (cf issue)
importation PropTypes et correction EsLint

2020-05-05 12:56 UTC, Justine810 submitted a review, later dismissed

2020-05-06 08:24 UTC, Froyj requested changes

2020-05-06 08:24 UTC, Froyj commented on src/components/ComponentMain/GlobalContainer.jsx
> +      periodeChecked: false
pour les booléens revoir le nommage ==> https://dev.to/michi/tips-on-naming-boolean-variables-cleaner-code-35ig

2020-05-06 08:24 UTC, Froyj commented on src/components/ComponentMain/GlobalContainer.jsx
> +    const moisF = localState.mois;
Penser aux destructurations ==> 
```
const { annee: anneeF, mois: moisF } = localState;
```

2020-05-06 12:30 UTC, Justine810 approved these changes

2020-05-07 13:44 UTC, Froyj approved these changes

2020-05-07 15:15 UTC, merged